[package]
name = "rs-rocket-horaire"
version = "0.1.0"
authors = ["Christian FOUCHER <christian.foucher@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
# error_chain = "*"
horaire = { git = "https://github.com/prisme60/rs-horaire.git" }
